CREATE DATABASE IF NOT EXISTS HABMSDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE HABMSDB;

CREATE TABLE IF NOT EXISTS Account (
    AID CHAR(10) NOT NULL PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    Password BINARY(64) NOT NULL,
    PID CHAR(18) NOT NULL UNIQUE,
    Phone CHAR(11) NOT NULL UNIQUE,
    Sex ENUM('M','F') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Doctor (
    DID CHAR(8) NOT NULL PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    Password BINARY(64) NOT NULL,
    Admin BOOLEAN NOT NULL,
    Department VARCHAR(30) NOT NULL,
    Description VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Schedule (
    SID INT NOT NULL PRIMARY KEY,
    DID CHAR(8) NOT NULL,
    STime DATETIME NOT NULL,
    ETime DATETIME NOT NULL,
    Capacity INT NOT NULL,
    Res INT NOT NULL,
    UNIQUE KEY uk_schedule_doctor_time (DID, STime, ETime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Appointment (
    SerialNumber INT NOT NULL AUTO_INCREMENT UNIQUE,
    APID CHAR(12) NOT NULL PRIMARY KEY,
    AID CHAR(10) NOT NULL,
    DID CHAR(8) NOT NULL,
    SID INT NOT NULL,
    Statu ENUM('Ok','Abandon','Done') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Doctor(DID,Name,Password,Admin,Department,Description)
VALUES ('00000000','Admin','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',TRUE,'管理',NULL)
ON DUPLICATE KEY UPDATE Name=VALUES(Name);
